name: progressive_blur
description: "(Experimental) Progressive blur implementation in Flutter."
version: 0.0.1
homepage: https://github.com/kekland/progressive_blur

environment:
  sdk: '>=3.5.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  flutter_shaders: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  shaders:
    - lib/shaders/progressive_blur.frag
